# Generated by Django 4.1.3 on 2023-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("announcement", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="book_equip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("phone_num", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("college", models.TextField()),
                ("classname", models.TextField()),
                ("appointment_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("equipment_name", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("location", models.TextField()),
                ("date", models.DateField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
