# Generated by Django 4.1.3 on 2023-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book_equip",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="book_equip",
            name="appointment_date",
            field=models.DateTimeField(),
        ),
    ]
