# Generated by Django 4.1.3 on 2023-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_book_equip_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_equip",
            name="appointment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
