# Generated by Django 4.1.3 on 2023-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_book_equip_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("laptop", "Laptop"),
                            ("printer", "Printer"),
                            ("scanner", "Scanner"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("description", models.TextField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="book_equip",
            name="equipment_name",
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
