# Generated by Django 4.1.3 on 2023-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_equipment_alter_book_equip_equipment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_equip",
            name="equipment_name",
            field=models.CharField(
                choices=[("scanner", "Scanner"), ("printer", "Printer")], max_length=50
            ),
        ),
    ]
