# Generated by Django 4.1.3 on 2023-03-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_book_equip_equipment_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="announcement",
            new_name="announcement_desc",
        ),
        migrations.AddField(
            model_name="announcement",
            name="announcement_title",
            field=models.TextField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
