# Generated by Django 4.1.3 on 2023-03-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_announcement_announcement_announcement_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_equip",
            name="equipment_name",
            field=models.ForeignKey(
                limit_choices_to={"is_available": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="api.equipment",
            ),
        ),
    ]
