# Generated by Django 4.1.3 on 2023-04-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_book_equip_equipment_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_equip",
            name="is_allotted",
            field=models.BooleanField(default=False),
        ),
    ]
