# Generated by Django 4.1.3 on 2023-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_book_equip_is_allotted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
