# Generated by Django 4.1.3 on 2023-04-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_equipment_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("designation", models.TextField()),
                ("ph_no", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="events",
            name="event_coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.teams",
            ),
        ),
    ]
