# Generated by Django 4.1.3 on 2023-04-21 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_events_event_coordinator_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teams",
            old_name="name",
            new_name="costudent_ambassador",
        ),
        migrations.AddField(
            model_name="teams",
            name="faculty_incharge",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teams",
            name="student_ambassador",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
