# Generated by Django 4.1.3 on 2023-04-21 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rename_costudent_ambassador_teams_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="event_coordinator",
        ),
        migrations.AddField(
            model_name="events",
            name="event_coordinator",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
