# Generated by Django 4.1.3 on 2023-04-21 10:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_events_event_coordinator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_coordinator",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True), size=None
            ),
        ),
    ]
