# Generated by Django 4.1.3 on 2023-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_events_event_coordinator"),
    ]

    operations = [
        migrations.CreateModel(
            name="event_heads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("designation", models.TextField()),
                ("ph_no", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="events",
            name="event_coordinator",
        ),
        migrations.AddField(
            model_name="events",
            name="event_coordinator",
            field=models.ManyToManyField(to="api.event_heads"),
        ),
    ]
