# Generated by Django 4.1.7 on 2023-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_event_heads_remove_events_event_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='events',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='events',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
    ]
