# Generated by Django 4.1.3 on 2023-05-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_events_about_events_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
