# Generated by Django 4.1.3 on 2023-05-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_events_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='status',
        ),
    ]
