# Generated by Django 4.1.3 on 2023-05-14 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_events_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 15, 7, 26, 707542, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
