# Generated by Django 4.1.3 on 2023-05-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_date_events_start_date_events_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='is_active',
        ),
    ]
