# Generated by Django 4.1.3 on 2023-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_events_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
