# Generated by Django 4.1.7 on 2023-05-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_events_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
