# Generated by Django 4.1.7 on 2023-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_teams_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
