# Generated by Django 4.1.7 on 2023-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_equipment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_heads',
            name='designation',
            field=models.CharField(choices=[('Student', 'Student'), ('Student Ambassador', 'Student Ambassador'), ('Student Co-Amabassador', 'Student Co-Amabassador'), ('Faculty in Charge', 'Faculty in Charge')], default='Others', max_length=50),
        ),
    ]
