FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN mkdir staticfiles

RUN python -m venv env
RUN . env/bin/activate

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["bash","entrypoint.sh"]